require "koriander.plugins"
require "koriander.core.options"
require "koriander.core.keymaps"
require "koriander.core.colors"
require "koriander.plugins.comment"
require "koriander.plugins.nvim-tree"
require "koriander.plugins.lualine"
require "koriander.plugins.telescope"
