#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep "HDMI connected") ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x0180 --rotate normal --right-of eDP
fi

bspc monitor eDP -d 1 2 3 4 5
bspc monitor HDMI -d 6 

bspc config border_width          0
bspc config window_gap            0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled

# Autostart
~/.config/polybar/launch.sh &
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
picom -bf &
nm-applet --indicator &
emacs --daemon &

# Cursor
xsetroot -cursor_name left_ptr &

xmodmap ~/.Xmodmap

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
