#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
# $HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/scripts/autostart.sh

bspc monitor -d I II III IV V VI

bspc config border_width 1
bspc config window_gap 8
bspc config focused_border_color "#1f1d29"
bspc config normal_border_color "#001f1d"

bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
